CREATE TABLE [dbo].[DIRINFO] (
    [ID]          INT             IDENTITY (1, 1) NOT NULL,
    [PARENT_ID]   INT             NULL,
    [FULLNAME]    NVARCHAR (2048) NOT NULL,
    [NAME]        NVARCHAR (1024) NOT NULL,
    [LEFT_INDEX]  INT             NULL,
    [RIGHT_INDEX] INT             NULL,
    [LEVEL_INDEX] INT             NULL,
    [PATH1]       INT             NULL,
    [PATH2]       INT             NULL,
    [PATH3]       INT             NULL,
    [PATH4]       INT             NULL,
    [PATH5]       INT             NULL,
    [PATH6]       INT             NULL,
    [PATH7]       INT             NULL,
    [PATH8]       INT             NULL,
    [PATH9]       INT             NULL,
    [PATH10]      INT             NULL,
    [PATH11]      INT             NULL,
    [PATH12]      INT             NULL,
    [PATH13]      INT             NULL,
    [PATH14]      INT             NULL,
    [PATH15]      INT             NULL,
    [PATH16]      INT             NULL,
    [PATH17]      INT             NULL,
    [PATH18]      INT             NULL,
    [PATH19]      INT             NULL,
    [PATH20]      INT             NULL,
    CONSTRAINT [PK__tmp_ms_x__3214EC27E9827703] PRIMARY KEY CLUSTERED ([ID] ASC)
);

