CREATE TABLE [dbo].[FILEINFO] (
    [ID]        INT             IDENTITY (1, 1) NOT NULL,
    [DIR_ID]    INT             NOT NULL,
    [FULLNAME]  NVARCHAR (2048) NOT NULL,
    [FILE_NAME] NVARCHAR (1024) NOT NULL,
    [FILE_EXT]  NCHAR (200)     NOT NULL,
    [FILE_SIZE] BIGINT          NOT NULL,
    CONSTRAINT [PK__FILEINFO__3214EC27E0BF1D5C] PRIMARY KEY CLUSTERED ([ID] ASC)
);

