CREATE TABLE [demo3].[DIRINFO] (
    [ID]          INT             IDENTITY (1, 1) NOT NULL,
    [LEFT_INDEX]  INT             NOT NULL,
    [RIGHT_INDEX] INT             NOT NULL,
    [NAME]        NVARCHAR (1024) NOT NULL,
    CONSTRAINT [PK_Table_1] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_DIRINFO302]
    ON [demo3].[DIRINFO]([LEFT_INDEX] ASC)
    INCLUDE([NAME]);


GO
CREATE NONCLUSTERED INDEX [IX_DIRINFO_4]
    ON [demo3].[DIRINFO]([RIGHT_INDEX] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_DIRINFO_3]
    ON [demo3].[DIRINFO]([LEFT_INDEX] ASC);

