CREATE TABLE [demo3].[FILEINFO] (
    [ID]     INT            NOT NULL,
    [DIR_ID] INT            NOT NULL,
    [NAME]   NVARCHAR (400) NOT NULL,
    [EXT]    NVARCHAR (200) NOT NULL,
    [SIZE]   BIGINT         NOT NULL,
    CONSTRAINT [PK_FILEINFO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FILEINFO_DIRINFO] FOREIGN KEY ([DIR_ID]) REFERENCES [demo3].[DIRINFO] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_FILEINFO301]
    ON [demo3].[FILEINFO]([EXT] ASC)
    INCLUDE([DIR_ID], [NAME], [SIZE]);

