CREATE TABLE [demo1].[DIRINFO] (
    [ID]        INT            IDENTITY (1, 1) NOT NULL,
    [PARENT_ID] INT            NULL,
    [NAME]      NVARCHAR (400) NOT NULL,
    CONSTRAINT [PK_DIRINFO] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_DIRINFO_NAME]
    ON [demo1].[DIRINFO]([NAME] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_DIRINFO_PARENTID]
    ON [demo1].[DIRINFO]([PARENT_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_DIRINFO_1]
    ON [demo1].[DIRINFO]([ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_DIRINFO]
    ON [demo1].[DIRINFO]([ID] ASC);

