CREATE TABLE [demo1].[FILEINFO] (
    [ID]     INT            NOT NULL,
    [DIR_ID] INT            NOT NULL,
    [NAME]   NVARCHAR (400) NOT NULL,
    [EXT]    NVARCHAR (200) NOT NULL,
    [SIZE]   BIGINT         NOT NULL,
    CONSTRAINT [PK_FILEINFO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FILEINFO_DIRINFO] FOREIGN KEY ([DIR_ID]) REFERENCES [demo1].[DIRINFO] ([ID])
);


GO
CREATE NONCLUSTERED INDEX [IX_FILEINFO_4]
    ON [demo1].[FILEINFO]([SIZE] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_FILEINFO_3]
    ON [demo1].[FILEINFO]([EXT] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_FILEINFO_2]
    ON [demo1].[FILEINFO]([NAME] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_FILEINFO_1]
    ON [demo1].[FILEINFO]([ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_FILEINFO]
    ON [demo1].[FILEINFO]([DIR_ID] ASC);

